# This is a Helm values file for configuring Cloudflare tunnel settings
# Helm is a Kubernetes package manager that uses these values to customize the deployment
# This file specifically configures:
# - Cloudflare tunnel settings for secure ingress
# - Ingress rules for Wazuh and Grafana services
# - HTTP headers and proxy settings
# - Resource limits and requests for the tunnel pods

tunnel:
  enabled: true
  token: "${CLOUDFLARE_TUNNEL_TOKEN}"
  protocol: "http2"
  noTLSVerify: false
  originServerName: "kubernetes.default.svc.cluster.local"
  warpRouting:
    enabled: false

ingress:
  - hostname: "${WAZUH_SUBDOMAIN}.${DOMAIN_NAME}"
    service: wazuh-dashboard
    path: "/"
    port: 443
  - hostname: "${GRAFANA_SUBDOMAIN}.${DOMAIN_NAME}"
    service: grafana
    path: "/"
    port: 3000

config:
  http2Origin: true
  disableChunkedEncoding: false
  httpHostHeader: ""
  proxySettings:
    connectTimeout: 30s
    tlsTimeout: 10s
    tcpKeepAlive: 30s
  headers:
    - key: X-Content-Type-Options
      value: nosniff
    - key: X-Frame-Options
      value: DENY
    - key: X-XSS-Protection
      value: "1; mode=block"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi